//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        public int magv { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public DateTime ngaysinh { get; set; }
        public Nullable<int> makhoa { get; set; }
        public Nullable<int> mamh { get; set; }
    
        public virtual Khoa Khoa { get; set; }
        public virtual MonHoc MonHoc { get; set; }

        public GiangVien(int magv, string hoten, string sdt, string diachi, DateTime ngaysinh, int? makhoa, int? mamh)
        {
            this.magv = magv;
            this.hoten = hoten;
            this.sdt = sdt;
            this.diachi = diachi;
            this.ngaysinh = ngaysinh;
            this.makhoa = makhoa;
            this.mamh = mamh;
        }

        public GiangVien()
        {
        }
    }
}
