//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLiSinhVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SinhVien()
        {
            this.Diems = new HashSet<Diem>();
        }
    
        public int masv { get; set; }
        public string hoten { get; set; }
        public string sdt { get; set; }
        public string diachi { get; set; }
        public DateTime ngaysinh { get; set; }
        public Nullable<int> malop { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Diem> Diems { get; set; }
        public virtual Lop Lop { get; set; }

        public SinhVien(int masv, string hoten, string sdt, string diachi, DateTime ngaysinh, int? malop)
        {
            this.masv = masv;
            this.hoten = hoten;
            this.sdt = sdt;
            this.diachi = diachi;
            this.ngaysinh = ngaysinh;
            this.malop = malop;
        }

        public override string ToString()
        {
            return this.hoten;
        }
    }
}
